version: '3'
services:

    dev:
        image: rust
        ports:
            - 3000:8080
        working_dir: /app
        volumes:
            - .:/app
            - cargo:/usr/local/cargo
        tmpfs:
            - /app/target:exec # Compiles into RAM, delete this line if you want it to compile to your storage.
        tty: true
        entrypoint: /bin/sh -c "cargo install cargo-watch && cargo watch -x 'run --bin main'"
        environment:
            - RUST_LOG=debug
            - LISTEN_PORT=8080
        env_file:
            - development.env
        restart: on-failure

volumes:
    cargo:
    target: